### ISSUE TITLE
Problem compiling under ROOT 5.X

### ISSUE THREAD

**Issue by cdreisbach** [AntokBatchelorMaintainers/antok#56]
I just got an e-mail describing the following problem:
![screenshot from 2017-04-19 11-10-49](https://cloud.githubusercontent.com/assets/7963601/25174120/b410954c-24f6-11e7-92c1-cdb01e45d602.png)

It seems that there is a problem is this code block:

antok/src/plotter.cxx:55 ff

#if ROOT_VERSION_CODE > ROOT_VERSION(6,0,0)
				int i_wp_bin = wp->histogram->GetXaxis()->FindFixBin(label);
#else
				wp->histogram->SetBit(**ROOT.TH1.kCanRebin,** false);
				**const** int i_wp_bin = wp->histogram->GetXaxis()->FindBin(label);
#endif

In my opinion: The const is wrong and there is a problem with the python part

**Comment by cdreisbach** [comment]
This should be the fix (Thanks to tproc):

 #else
 -				wp->histogram->SetBit(ROOT.TH1.kCanRebin, false);
 -				const int i_wp_bin = wp->histogram->GetXaxis()->FindBin(label);
 +				wp->histogram->SetBit(TH1::kCanRebin, false);
 +				int i_wp_bin = wp->histogram->GetXaxis()->FindBin(label);
  #endif

**Comment by stefan-wallner** [comment]
Pullrequest #57 fixes the bug.
